export const projects = [
	{
		date: "Octobre 2023",
		title: "Webdocumentaire",
		description: "Projet de fin d'études en groupe de 5, 6 mois de travail, ",
		images: [
			"/assets/eye-care/login.png",
			"/assets/eye-care/home.png",
			"/assets/eye-care/articles.png",
			"/assets/eye-care/comments.png",
			"/assets/eye-care/tests.png",
			"/assets/eye-care/profile.png",
		],
		up: true,
	},
	{
		date: "Mars 2024",
		title: "Commande de sushi",
		description: "Projet de fin d'études en groupe de 5, 6 mois de travail, ",
		images: [
			"/assets/eye-care/login.png",
			"/assets/eye-care/home.png",
			"/assets/eye-care/articles.png",
			"/assets/eye-care/comments.png",
			"/assets/eye-care/tests.png",
			"/assets/eye-care/profile.png",
		],
	},
	{
		date: "Mars 2024",
		title: "Commande de sushi",
		description: "Projet de fin d'études en groupe de 5, 6 mois de travail, ",
		images: [
			"/assets/eye-care/login.png",
			"/assets/eye-care/home.png",
			"/assets/eye-care/articles.png",
			"/assets/eye-care/comments.png",
			"/assets/eye-care/tests.png",
			"/assets/eye-care/profile.png",
		],
		up: true,
	},
	{
		date: "2024-2025",
		title: "Eye-care",
		description: "Projet de fin d'études en groupe de 5, 6 mois de travail,",
		images: [
			"/assets/eye-care/login.png",
			"/assets/eye-care/home.png",
			"/assets/eye-care/articles.png",
			"/assets/eye-care/comments.png",
			"/assets/eye-care/tests.png",
			"/assets/eye-care/profile.png",
		],
	},
];
