export const projects = [
	{
		date: "Octobre 2023",
		title: "Webdocumentaire",
		description: "Projet de fin d'études en groupe de 5, 6 mois de travail, ",
		images: [
			"/assets/octobre-rose/intro.png",
			"/assets/octobre-rose/home.png",
			"/assets/octobre-rose/home2.png",
			"/assets/octobre-rose/interview.png",
			"/assets/octobre-rose/video.png",
		],
		up: true,
		technologies: ["HTML", "CSS", "Javascript"],
		github: "https://github.com/ArnoLM7/Webdocumentaire-Octobre-rose",
	},
	{
		date: "Mars 2024",
		title: "Commande de sushi",
		description: "Projet de fin d'études en groupe de 5, 6 mois de travail, ",
		images: [
			"/assets/nagashima/home.png",
			"/assets/nagashima/liste.png",
			"/assets/nagashima/thon.png",
			"/assets/nagashima/paiement.png",
		],
		mobile: true,
		technologies: ["NodeJS", "Angular", "Bootstrap"],
		github: "https://github.com/RubenDavidAbreu/nagashima",
	},
	{
		date: "Juin 2024",
		title: "Questionnaire",
		description: "Projet de fin d'études en groupe de 5, 6 mois de travail, ",
		images: ["/assets/jdg-fred.gif"],
		up: true,
		technologies: ["Figma", "Photoshop"],
	},
	{
		date: "2024-2025",
		title: "Eye-care",
		description: "Projet de fin d'études en groupe de 5, 6 mois de travail,",
		images: [
			"/assets/eye-care/login.png",
			"/assets/eye-care/home.png",
			"/assets/eye-care/articles.png",
			"/assets/eye-care/comments.png",
			"/assets/eye-care/tests.png",
			"/assets/eye-care/profile.png",
		],
		technologies: ["Symfony", "ReactJS", "SCSS"],
		github: "https://github.com/Raphi04/Eye-Care_SAE501",
		web: "https://eye-care-project.netlify.app/",
	},
];
